export class GarageInfo{
    created_at?: Date;
    updated_at?: Date;
    created_by?: any;
    updated_by?: any;
    garage_id?: string;
    mobile_number?: string;
    garage_name?: string;
    address?: string;
    pin?: number;
    email?: string;
    website?: string;
    established_date?: string;
    owner_name?: string;
    vat?: number;
    st?: number;
    gst?: number;
    parts_commission?: number;
    gp_commission?: number;
    subscription_end_date?: Date;
    active?: boolean;
    type?: string;
    vat_number?: string;
    st_number?: string;
    gst_number?: string;
    is_st_applicable?:boolean;
    is_vat_applicable?:boolean;
    logo_url?:string;
    is_gst_applicable?:boolean;
    parts_gst?: number;
    service_gst?:number;
    inventory_enabled?:boolean;
    geo_coordinates?:string;
    estimate_terms?:string;
    invoice_terms?:string;
    is_payment_gateway_enabled?:boolean;
    part_issuance_enabled?:boolean;
    sms_sender_name?:string;
    part_issuance_enabled_date?:Date;
    state?:string;
    referral_code?:string;
    google_mybusiness_link?:string;
    country_code?: string;
    time_zone?:string;
    vehicle_id?:string;
    group_id?:string;
    is_tax_applicable?: boolean;
     phone_code?: number;
     currency_code?: string;
     language_code?:string;
}